name: tview
version: 0.2.6
usage: "Browse 'helm template' output per-file in a split TUI"
description: |
  Renders 'helm template' to a temp directory and opens a split-view TUI:
  left shows readable filenames (with kind), right shows a live preview.
  Supports content filtering with -s/--search to list only matching files,
  highlighting matches in the preview (uses ripgrep if available).

command: "$HELM_PLUGIN_DIR/tview.sh"
