name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Derive version
        id: ver
        run: echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
      - name: Prepare tarball
        run: |
          mkdir -p dist
          tar -C plugin -czf dist/tview-${{ steps.ver.outputs.version }}.tgz .
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: tview ${{ github.ref_name }}
          files: |
            dist/*.tgz
